### ISSUE TITLE
PegaScape HBMenu Issue (Using PegaScape Step #2)

### ISSUE THREAD

**Issue by sigma-theta** [AtlasNX/Homebrew-Guide#107]
I am trying to launch HBMenu through PegaScape on my 4.1.0 patched Switch but nothing shows up after I get the success notification and click on the album button. It's just a blank menu screen with only a prompt in the bottom right corner of the screen that says A Button = OK. I tried reformatting my SD Card, updating hbmenu and everything but nothing worked so far.

https://user-images.githubusercontent.com/92057117/136273222-31ae9f0b-4140-4155-b8f6-d59541ee1b4c.mp4

**Comment by WaitXie** [comment]
> I successfully booted into Hekate.

How do you boot into Hekate. I am facing the same issue.
