### ISSUE TITLE
Comparing Custom Firmwares inaccuracy

### ISSUE THREAD

**Issue by Delerium** [AtlasNX/Homebrew-Guide#15]
Comparing Custom Firmwares page states that SX-OS is not capable of a NAND dump, which is not entirely accurate.  NAND dumps are usually done from the payload not the custom firmware, so if you are comparing apples to apples, the dongle that delivers the payload and runs SX-OS is fully capable of backing up NAND.

**Comment by noahc3** [comment]
Done
