### ISSUE TITLE
Accessing RCM page from [Before Starting] page dosen't exist

### ISSUE THREAD

**Issue by abc112116** [AtlasNX/Homebrew-Guide#24]
https://guide.sdsetup.com/gettingstarted/accessingrcm dosen't exist. This made me confused for a while why it's not go out anywhere from https://guide.sdsetup.com/gettingstarted/beforestarting

**Comment by noahc3** [comment]
oh dear, I pushed the wrong branch

gimme a few minutes

**Comment by noahc3** [comment]
fixed
