### ISSUE TITLE
Dead "test payload" link in `checkingrcm.rst` 

### ISSUE THREAD

**Issue by nwelchr** [AtlasNX/Homebrew-Guide#42]
https://github.com/AtlasNX/Homebrew-Guide/blob/master/gettingstarted/checkingrcm.rst

The test payload (i.e. `fusee-test.bin`) file link just sends you to a 404 google drive error. The link should just need updating.

**Comment by noahc3** [comment]
Unfortunately I permanently deleted it from my Google Drive and I lost the source when I corrupted a VM a while back. If someone still has a copy I'd appreciate it if they could send it to me, otherwise I'll get around to rewriting it some time soon.

**Comment by fosspill** [comment]
So... What would one do instead of following that step? Just skip it and hope for the best?

**Comment by DanielC-08** [comment]
@fosspill I just use hekate to see if it works.

**Comment by noahc3** [comment]
We now have a replacement payload thanks to @shchmue, I'll get this uploaded on the guide soon.
[fusee-test.zip](https://github.com/AtlasNX/Homebrew-Guide/files/3890384/fusee-test.zip)

**Comment by TechGeekGamer** [comment]
Soon ™️ ?

**Comment by noahc3** [comment]
Fixed in 1db22ad0c59f8a322ed5e878ac7dae32047369ff.
