### ISSUE TITLE
Main guide is out of date

### ISSUE THREAD

**Issue by aidanhs** [AtlasNX/Homebrew-Guide#48]
In particular, the emummc page is missing

 - https://switch.homebrew.guide/hacking/emummc
 - https://pubdev.switch.homebrew.guide/hacking/emummc

**Comment by tumGER** [comment]
Refer to https://github.com/AtlasNX/emuMMC-Guides for now.

**Comment by noahc3** [comment]
I have a week break in a week and a half, I'll get the guide finished and everything published then.

**Comment by hax4dazy** [comment]
[The second emummc thing does still work tho..... ](https://pubdev.switch.homebrew.guide/hacking/emummc)

**Comment by NicholeMattera** [comment]
The guide that Tom linked to defiantly works.

**Comment by noahc3** [comment]
Nichole added a proper EmuMMC guide a while ago.
