### ISSUE TITLE
Guide is unclear at hacking/fuseegelee/aftersetup

### ISSUE THREAD

**Issue by fortepc** [AtlasNX/Homebrew-Guide#49]
[Tap ‘Launch > CFW’](https://switch.homebrew.guide/hacking/fuseegelee/aftersetup#launching-atmosphere-cfw`) is unclear because when following this for the first time, there is no option that is simply `CFW` under the launch button. It's got `CFW (SYSNAND)` AND `CFW (EMUMMC)`. 
I'm currently at this step and neither one is working. When trying to launch `CFW (SYSNAND)` I get this error. 

```
Initializing...
Found pkg1 ('20191021113848')
Identified Pkg1 and Keyblob 10
Found fss0, Atmosphere 0.10.1-71B220A4
max HOS supported: 9.1.0
Unpacking and loading components.. done!
Loaded Pkg1 & keyblob
Generated keys
loaded warmboot and secmon
Read Pkg2
Pkg2 decryption failed! 
Is Sept updated?
Failed to launch HOS!
Press any key...
```

**Comment by hax4dazy** [comment]
what's your switches firmware at?

**Comment by fortepc** [comment]
I did the troubleshooting discussion in the Discord server, this was only meant to be a report for the unclear instructions.

**Comment by noahc3** [comment]
c0299d137ff99825dd249ac7616831e967a581bc
