### ISSUE TITLE
Tegra RCM byte code info suggestion

### ISSUE THREAD

**Issue by C4J3** [AtlasNX/Homebrew-Guide#50]
So I was trying to hack my switch earlier and the test payload binary is not available at the provided link. I read online that you can just use any payload to test but when I did nothing happened on the device. I went and got help on the switch haxing discord and was told that the line: Smashed the stack with a 0x0000 byte SETUP request! means that no data was sent. I was thinking that adding a few common things like that at the bottom of the page with what they mean could be useful for user troubleshooting. Maybe in or after the error box at the bottom of the step 2 TegraRCMGui instructions section

**Comment by TechGeekGamer** [comment]
When it says 0x0000 it most likely means the switch is patched. You could always try another cable, but not likely that it would work.

**Comment by noahc3** [comment]
bd9aca48f3ec2436e76318285a72bce37f917cd9
