### ISSUE TITLE
Test payload doesn't work

### ISSUE THREAD

**Issue by Supermigue2000** [AtlasNX/Homebrew-Guide#52]
Hi! The test payload in checking RCM (https://switch.homebrew.guide/gettingstarted/checkingrcm#step-0-what-you-will-need) doesen't work.

**Comment by Supermigue2000** [comment]
Hi! The test payload in checking RCM (https://switch.homebrew.guide/gettingstarted/checkingrcm#step-0-what-you-will-need) doesen't work.

**Comment by TechGeekGamer** [comment]
#42
