### ISSUE TITLE
Add warning about game card update

### ISSUE THREAD

**Issue by augustjanse** [AtlasNX/Homebrew-Guide#8]
Users upgrading from lower firmwares risk inadvertently updating their game card firmware when upgrading. CDNX regrettably lulls users into a false sense of security by creating a pretty much useless hekate config in the wrong place. The guide should warn users about this, and detail what they must to manually to keep their game card firmware.

**Comment by noahc3** [comment]
Guide will be getting a makeover soon (this week hopefully), I'll make sure to include this information and a guide to enable nogc as well.

**Comment by augustjanse** [comment]
I think newer versions of Hekate have nogc enabled by default, thus rendering this issue moot. This is just from my memory though, I'll close if anyone can confirm.

**Comment by noahc3** [comment]
Hekate does indeed have autonogc enabled by default.
